{
 "title": "K8S Nodes",
 "description": "Kubernetes Node Metrics with Elasticsearch backend",
 "tags": [
  "kubernetes",
  "nodes",
  "elasticsearch",
  "metricbeat 7.3.2"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "elasticsearch" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{\"find\": \"terms\", \"field\": \"cluster\", \"size\": \"100\"}"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.namespace\", \"size\": 300, \"query\": \"cluster:$cluster\"}"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.node.name\", \"query\": \"kubernetes.namespace:$namespace\"}"
   },
   {
    "name": "shorthost",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.node.name\", \"query\": \"metricset.name:node AND kubernetes.node.name:$node\"}"
   },
   {
    "name": "host",
    "query": "{\"find\": \"terms\", \"field\": \"host.name\", \"query\": \"metricset.name:node AND host.name:/$shorthost([^0-9].*)?/\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.load.norm.1",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.name:load AND host.name:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.node.name:$node AND kubernetes.node.status.ready:true",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.cpu.capacity.cores",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kubernetes.node.name:$node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "host.name:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.fs.capacity.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kubernetes.node.name:$node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.start_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kubernetes.node.name:$node",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.iowait.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "system.cpu.nice.pct",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "system.cpu.softirq.pct",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "system.cpu.steal.pct",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "system.cpu.system.pct",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "system.cpu.user.pct",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "(metricset.module:system OR event.module:system) AND metricset.name:cpu AND host.name:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.free",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "system.memory.used.bytes",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "metricset.name:memory AND host.name:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "description": "Negative values means outgoing traffic",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "{{system.network.name}} incoming",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.network.name",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.in.bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "metricset.name:network AND host.name:$host AND NOT system.network.name:/lo|bond[0-9]|cbr[0-9]|veth.*/",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{system.network.name}} outgoing",
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.network.name",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.network.out.bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "metricset.name:network AND host.name:$host AND NOT system.network.name:/lo|bond[0-9]|cbr[0-9]|veth.*/",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "system.diskio.name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.diskio.io.time",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1m" },
       "type": "derivative"
      }
     ],
     "query": "host.name:$host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Filesystem - All Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.fs.used.bytes$MAX",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kubernetes.node.name:$node",
     "timeField": "@timestamp"
    },
    {
     "alias": "free",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.fs.available.bytes$MAX",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "kubernetes.node.name:$node",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}