{
 "title": "Kubernetes Resources",
 "tags": [
  "kubernetes",
  "metricbeat",
  "elasticsearch",
  "metricbeat 7.3.2"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "elasticsearch" },
   {
    "name": "region",
    "label": "Region",
    "query": "{\"find\": \"terms\", \"field\": \"cloud.region\", \"size\": 300}"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{\"find\": \"terms\", \"field\": \"cluster\", \"query\":\"cloud.region:$region\"}"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.namespace\", \"size\": 300, \"query\": \"cluster:$cluster\"}"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.deployment.name\", \"query\":\"cluster:$cluster\", \"size\": 300}"
   }
  ]
 },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods In Wait State",
   "type": "graph",
   "description": "Waiting Pods\n\nPods unready but not terminated.\n\nReasons:\n- ErrImagePull \n- CrashLoopBackOff\n- ImagePullBackOff\n- ContainerCreating",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{cloud.region}}-{{kubernetes.namespace}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "cloud.region",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "kubernetes.namespace",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.pod.name",
       "id": "1",
       "meta": {},
       "settings": {
        "precision_threshold": null
       },
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.status.phase:pending AND cloud.region:$region AND cluster:$cluster AND kubernetes.namespace:$namespace",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pods In Running State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{cloud.region}}-{{kubernetes.namespace}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "cloud.region",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "kubernetes.namespace",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.pod.name",
       "id": "1",
       "meta": {},
       "settings": {
        "precision_threshold": null
       },
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.status.phase:running AND cloud.region:$region AND cluster:$cluster AND kubernetes.namespace:$namespace",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unavailable Replicas per Deployment (Replicas Desired - Replicas Ready)",
   "type": "graph",
   "description": "Replicas Desired should always be equal to Replicas Ready.\n\nThis should always be 0 zero (except during deployment), if it is greater than 0 you may not have redundancy, adequate capacity, or you may be down.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.deployment.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.deployment.replicas.unavailable",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "kubernetes.namespace:$namespace AND kubernetes.deployment.name:$deployment AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Pod Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Percent of Memory Limit In Use",
   "type": "graph",
   "description": "Memory Limits\n\nMemory limits is part of your helm values.\n\nThis graph shows the percentage of that limit in use.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.container.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.container.memory.usage.limit.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "cloud.region:$region AND cluster:$cluster AND kubernetes.namespace:$namespace",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Most Memory-Intensive Pods",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "{{cloud.region}} - {{kubernetes.pod.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.pod.name",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "cloud.region",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.pod.memory.usage.bytes",
       "id": "1",
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "max"
      }
     ],
     "query": "cloud.region:$region AND cluster:$cluster AND kubernetes.namespace:$namespace",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Most CPU-Intensive Pods (By Cores)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "alias": "{{cloud.region}} - {{kubernetes.pod.name}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.pod.name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "cloud.region",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.pod.cpu.usage.nanocores",
       "id": "1",
       "inlineScript": "_value/1000000000",
       "meta": {},
       "settings": { "script": { "inline": "_value/1000000000" } },
       "type": "max"
      }
     ],
     "query": "cloud.region:$region AND cluster:$cluster AND kubernetes.namespace:$namespace",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Environment Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory Available per Host (Higher is better)",
   "type": "graph",
   "description": "Memory Available To The Scheduler For Deployments\n\nOnly used at deployment time, memory available for new containers on a node.\n\nIf this limit is reached your deployment/scale will remain in an unscheduled state.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cluster",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "kubernetes.node.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.memory.available.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "cloud.region:$region AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pods Available per Node (Pods Limit - Pods ready per node)",
   "type": "graph",
   "description": "Pod Limits\n\nPipeline teams set a limit on the number of pods that can be deployed to a node.\n\nIf this limit is reached your deployment/scale will remain in an unscheduled state.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.node.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.pod.name",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {
        "precision_threshold": null
       },
       "type": "cardinality"
      },
      {
       "field": "kubernetes.node.pod.allocatable.total",
       "hide": true,
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "select field",
       "id": "5",
       "meta": {},
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "4" },
        { "name": "var2", "pipelineAgg": "1" }
       ],
       "settings": { "script": "params.var1 - params.var2" },
       "type": "bucket_script"
      }
     ],
     "query": "kubernetes.pod.status.ready:true OR _exists_:kubernetes.node.pod.allocatable.total",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory Pressured Node",
   "type": "graph",
   "description": "Memory Pressure\n\nKubernetes defines a point at which memory is considered \"pressured\", at that point pods which have exceeded their Request.Limit are subject to eviction.\n\nThis metric is memory capacity of the node minus the total memory consumed by all the pods on that node.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.node.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.node.memory.workingset.bytes",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {
        "missing": null
       },
       "type": "max"
      }
     ],
     "query": "cloud.region:$region AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}