{
 "title": "K8S Cluster",
 "tags": [
  "kubernetes",
  "elasticsearch",
  "metricbeat 7.3.2"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "query": "elasticsearch" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "{\"find\": \"terms\", \"field\": \"cluster\"}"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.namespace\", \"size\": 300, \"query\": \"cluster:$cluster\"}"
   },
   {
    "name": "hostname",
    "query": "{\"find\": \"terms\", \"field\": \"host.name\", \"query\":\"kubernetes.namespace:$namespace\", \"size\": 300}"
   },
   {
    "name": "container",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.container.name\", \"size\": 300, \"query\":\"host.name:$hostname AND cluster:$cluster\"}"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.pod.name\", \"size\": 300, \"query\":\"metricset.name:container AND kubernetes.container.name:$container AND cluster:$cluster\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "expr": "sum(kubelet_running_container_count{instance=~\"^$Node$\",job=\"kubelets\"})",
     "metrics": [
      {
       "field": "kubernetes.container.id",
       "id": "1",
       "meta": {},
       "settings": { "precision_threshold": 40000 },
       "type": "cardinality"
      }
     ],
     "query": "host.name:$hostname  kubernetes.container.name:$container AND kubernetes.container.status.phase:running AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Waiting containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "expr": "sum(kubelet_running_container_count{instance=~\"^$Node$\",job=\"kubelets\"})",
     "metrics": [
      {
       "field": "kubernetes.container.id",
       "id": "1",
       "meta": {},
       "settings": { "precision_threshold": 40000 },
       "type": "cardinality"
      }
     ],
     "query": "host.name:$hostname  AND kubernetes.container.name:$container AND kubernetes.container.status.phase:waiting AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Terminated containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "expr": "sum(kubelet_running_container_count{instance=~\"^$Node$\",job=\"kubelets\"})",
     "metrics": [
      {
       "field": "kubernetes.container.id",
       "id": "1",
       "meta": {},
       "settings": { "precision_threshold": 40000 },
       "type": "cardinality"
      }
     ],
     "query": "host.name:$hostname  AND kubernetes.container.name:$container AND kubernetes.container.status.phase:terminated AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Running",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.container.id",
       "id": "1",
       "meta": {},
       "settings": { "precision_threshold": 40000 },
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.container.status.phase:running  AND kubernetes.container.name:$container AND cluster:$cluster AND host.name:$hostname",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Non-Running Containers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Waiting",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.container.id",
       "id": "1",
       "meta": {},
       "settings": { "precision_threshold": 40000 },
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.container.status.phase:waiting  AND host.name:$hostname AND kubernetes.container.name:$container AND cluster:$cluster",
     "timeField": "@timestamp"
    },
    {
     "alias": "Terminated",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "kubernetes.container.id",
       "id": "1",
       "meta": {},
       "settings": { "precision_threshold": 40000 },
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.container.status.phase:terminated  AND host.name:$hostname AND kubernetes.container.name:$container AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Running pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "expr": "sum(kubelet_running_pod_count{instance=~\"^$Node$\",job=\"kubelets\"})",
     "metrics": [
      {
       "field": "kubernetes.pod.name",
       "id": "1",
       "meta": {},
       "settings": { "precision_threshold": 40000 },
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:$container*  AND host.name:$hostname AND kubernetes.pod.status.phase:running AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 1, "trimEdges": 3 }, "type": "date_histogram" }
     ],
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",instance=~\"^$Node$\"})",
     "metrics": [
      {
       "field": "kubernetes.container.memory.workingset.bytes$SUM",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname  AND kubernetes.container.name:$container AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Filesystem used space",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 1, "trimEdges": 3 }, "type": "date_histogram" }
     ],
     "expr": "sum (container_fs_usage_bytes{device=\"/dev/xvda9\",id=\"/\",instance=~\"^$Node$\"})",
     "metrics": [
      {
       "field": "kubernetes.container.rootfs.used.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname  AND kubernetes.container.name:$container AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Filesystem total space",
   "type": "graph",
   "description": "When choosing multiple hosts this metric will show the average FS space",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.node.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 1, "trimEdges": 3 }, "type": "date_histogram" }
     ],
     "expr": "sum (container_fs_usage_bytes{device=\"/dev/xvda9\",id=\"/\",instance=~\"^$Node$\"})",
     "metrics": [
      {
       "field": "kubernetes.container.rootfs.capacity.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.name:$hostname  AND kubernetes.container.name:$container AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "expr": "sum(kubelet_running_pod_count{instance=~\"^$Node$\",job=\"kubelets\"})",
     "metrics": [
      {
       "field": "kubernetes.pod.name",
       "id": "1",
       "meta": {},
       "settings": { "precision_threshold": 40000 },
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.pod.name:$container*  AND host.name:$hostname AND kubernetes.pod.status.phase:pending AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 1, "trimEdges": 3 }, "type": "date_histogram" }
     ],
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",instance=~\"^$Node$\"})",
     "metrics": [
      {
       "field": "kubernetes.container.memory.available.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "host.name:$hostname  AND kubernetes.container.name:$container AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.pod.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",instance=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}",
     "metrics": [
      {
       "field": "kubernetes.container.cpu.usage.core.ns",
       "hide": true,
       "id": "1",
       "inlineScript": "_value/1000000000",
       "meta": {},
       "settings": { "script": { "inline": "_value/1000000000" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "host.name:$hostname  AND kubernetes.container.name:$container AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pod Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.pod.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "30" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$Node$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}",
     "metrics": [
      {
       "field": "kubernetes.container.memory.workingset.bytes$MAX",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "host.name:$hostname  AND kubernetes.container.name:$container AND cluster:$cluster",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Pod Network i/o",
   "type": "graph",
   "description": "Negative values means outgoing traffic",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "{{kubernetes.pod.name}} - received",
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.pod.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "sort_desc(sum by (pod_name) (rate (container_network_receive_bytes_total{instance=~\"^$Node$\",name!=\"\", pod_name=~\".*\"}[1m]) ))",
     "legendFormat": "{{ pod_name }}Reveived",
     "metrics": [
      {
       "field": "kubernetes.pod.network.rx.bytes",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "event.module: kubernetes  AND  metricset.name: pod AND host.name:$hostname AND cluster:$cluster AND kubernetes.pod.name:$pod",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{kubernetes.pod.name}} - sent",
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.pod.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "- sort_desc(sum by (pod_name) (rate (container_network_transmit_bytes_total{instance=~\"^$Node$\",name!=\"\", pod_name=~\".*\"}[1m]) ))",
     "legendFormat": "{{ pod_name }}Sent",
     "metrics": [
      {
       "field": "kubernetes.pod.network.tx.bytes",
       "hide": true,
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": { "unit": "1s" },
       "type": "derivative"
      }
     ],
     "query": "event.module: kubernetes  AND metricset.name: pod AND host.name:$hostname AND cluster:$cluster AND kubernetes.pod.name:$pod",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}