{
 "title": "Cloudwatch AWS/AmazonMQ",
 "tags": [
  "AWS",
  "Metricbeat 7.5",
  "Cloudwatch"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1s,5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "broker",
    "label": "Broker",
    "query": "{\"find\": \"terms\", \"field\": \"aws.cloudwatch.dimensions.Broker\"}"
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": "{\"find\": \"terms\", \"field\": \"aws.cloudwatch.dimensions.Queue\"}"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "{\"find\": \"terms\", \"field\": \"aws.cloudwatch.dimensions.Topic\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Total producers",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.TotalProducerCount.max",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total consumers",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.TotalConsumerCount.max",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "max"
      }
     ],
     "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unclean shutdown",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "ournalFilesForFullRecovery",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.JournalFilesForFullRecovery.max",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "max"
      }
     ],
     "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Clean shutdown",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "ournalFilesForFastRecovery",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.JournalFilesForFastRecovery.max",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "max"
      }
     ],
     "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Broker resource metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap usage per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "HeapUsage (broker: {{aws.cloudwatch.dimensions.Broker}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.HeapUsage.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "CPU utilization per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "CPUUtilization (broker: {{aws.cloudwatch.dimensions.Broker}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.CpuUtilization.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Total consumers per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "TotalConsumerCount (broker: {{aws.cloudwatch.dimensions.Broker}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.TotalConsumerCount.count",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Storage limit usage per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "StorePercentUsage (broker: {{aws.cloudwatch.dimensions.Broker}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.StorePercentUsage.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Network in per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "NetworkIn (broker: {{aws.cloudwatch.dimensions.Broker}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.NetworkIn.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Network out per broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "NetworkOut (broker: {{aws.cloudwatch.dimensions.Broker}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.NetworkOut.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker)",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Destination metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue size per queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "QueueSIze (broker: {{aws.cloudwatch.dimensions.Broker}}, service: {{aws.cloudwatch.dimensions.Queue}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Queue",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.QueueSize.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Queue AND aws.cloudwatch.dimensions.Queue:$queue)",
       "timeField": "@timestamp"
      },
      {
       "alias": "QueueSIze (broker: {{aws.cloudwatch.dimensions.Broker}}, topic: {{aws.cloudwatch.dimensions.Topic}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Topic",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.QueueSize.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Topic AND aws.cloudwatch.dimensions.Topic:$topic)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Subscribed consumers per destination",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ConsumerCount (broker: {{aws.cloudwatch.dimensions.Broker}}, service: {{aws.cloudwatch.dimensions.Queue}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Queue",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.ConsumerCount.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Queue AND aws.cloudwatch.dimensions.Queue:$queue)",
       "timeField": "@timestamp"
      },
      {
       "alias": "ConsumerCount (broker: {{aws.cloudwatch.dimensions.Broker}}, topic: {{aws.cloudwatch.dimensions.Topic}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Topic",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.ConsumerCount.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Topic AND aws.cloudwatch.dimensions.Topic:$topic)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Total messages sent to consumers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "DispatchCount (broker: {{aws.cloudwatch.dimensions.Broker}}, service: {{aws.cloudwatch.dimensions.Queue}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Queue",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.DispatchCount.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Queue AND aws.cloudwatch.dimensions.Queue:$queue)",
       "timeField": "@timestamp"
      },
      {
       "alias": "DispatchCount  (broker: {{aws.cloudwatch.dimensions.Broker}}, topic: {{aws.cloudwatch.dimensions.Topic}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Topic",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.DispatchCount.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Topic AND aws.cloudwatch.dimensions.Topic:$topic)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Producers per destination",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ProducerCount (broker: {{aws.cloudwatch.dimensions.Broker}}, service: {{aws.cloudwatch.dimensions.Queue}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Queue",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.ProducerCount.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Queue AND aws.cloudwatch.dimensions.Queue:$queue)",
       "timeField": "@timestamp"
      },
      {
       "alias": "ProducerCount  (broker: {{aws.cloudwatch.dimensions.Broker}}, topic: {{aws.cloudwatch.dimensions.Topic}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Queue",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.ProducerCount.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Topic AND aws.cloudwatch.dimensions.Topic:$topic)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Total messages received per destination",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "ReceiveCount (broker: {{aws.cloudwatch.dimensions.Broker}}, service: {{aws.cloudwatch.dimensions.Queue}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Queue",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.ReceiveCount.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Queue AND aws.cloudwatch.dimensions.Queue:$queue)",
       "timeField": "@timestamp"
      },
      {
       "alias": "ReceiveCount (broker: {{aws.cloudwatch.dimensions.Broker}}, topic: {{aws.cloudwatch.dimensions.Topic}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Topic",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.ReceiveCount.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Topic AND aws.cloudwatch.dimensions.Topic:$topic)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Total messages sent per destination",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "EnqueueCount (broker: {{aws.cloudwatch.dimensions.Broker}}, queue: {{aws.cloudwatch.dimensions.Queue}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Queue",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.EnqueueCount.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Queue AND aws.cloudwatch.dimensions.Queue:$queue)",
       "timeField": "@timestamp"
      },
      {
       "alias": "EnqueueCount (broker: {{aws.cloudwatch.dimensions.Broker}}, topic: {{aws.cloudwatch.dimensions.Topic}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Topic",
         "id": "5",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "@timestamp",
         "id": "3",
         "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "aws.metrics.EnqueueCount.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Topic AND aws.cloudwatch.dimensions.Topic:$topic)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Expired count per destination",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "ExpiredCount (broker: {{aws.cloudwatch.dimensions.Broker}}, queue: {{aws.cloudwatch.dimensions.Queue}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Queue",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.ExpiredCount.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Queue AND aws.cloudwatch.dimensions.Queue:$queue)",
       "timeField": "@timestamp"
      },
      {
       "alias": "ExpiredCount (broker: {{aws.cloudwatch.dimensions.Broker}}, topic: {{aws.cloudwatch.dimensions.Topic}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Topic",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.ExpiredCount.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Topic AND aws.cloudwatch.dimensions.Topic:$topic)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Broker message latency per destination",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "EnqueueTime (broker: {{aws.cloudwatch.dimensions.Broker}}, service: {{aws.cloudwatch.dimensions.Queue}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Queue",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.EnqueueTime.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Queue AND aws.cloudwatch.dimensions.Queue:$queue)",
       "timeField": "@timestamp"
      },
      {
       "alias": "EnqueueTime  (broker: {{aws.cloudwatch.dimensions.Broker}}, topic: {{aws.cloudwatch.dimensions.Topic}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Topic",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.EnqueueTime.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Topic AND aws.cloudwatch.dimensions.Topic:$topic)",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Avg memory limit usage per destination",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "DispatchCount (broker: {{aws.cloudwatch.dimensions.Broker}}, service: {{aws.cloudwatch.dimensions.Queue}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Queue",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.MemoryUsage.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Queue AND aws.cloudwatch.dimensions.Queue:$queue)",
       "timeField": "@timestamp"
      },
      {
       "alias": "DispatchCount  (broker: {{aws.cloudwatch.dimensions.Broker}}, topic: {{aws.cloudwatch.dimensions.Topic}})",
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Broker",
         "id": "4",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.Topic",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.MemoryUsage.max",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "aws.cloudwatch.namespace:AWS\\/AmazonMQ AND (_exists_:aws.cloudwatch.dimensions.Broker AND aws.cloudwatch.dimensions.Broker:$broker) AND (_exists_:aws.cloudwatch.dimensions.Topic AND aws.cloudwatch.dimensions.Topic:$topic)",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}