{
 "title": "Cloudwatch AWS/RDS",
 "tags": [
  "AWS",
  "Cloudwatch",
  "RDS",
  "Metricbeat 7.5"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "elasticsearch" },
   {
    "name": "Region",
    "query": "{ \"find\": \"terms\", \"field\": \"cloud.region\" }"
   },
   {
    "name": "DB_instance",
    "query": "{ \"find\": \"terms\", \"field\": \"aws.cloudwatch.dimensions.DBInstanceIdentifier\", \"query\": \"cloud.region:$Region\" }"
   }
  ]
 },
 "panels": [
  {
   "title": "Database connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.DatabaseConnections.max",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "aws.cloudwatch.dimensions.DBInstanceIdentifier:$DB_instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Free storage space",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.FreeStorageSpace.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Freeable memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.FreeableMemory.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Utilisation by DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{aws.cloudwatch.dimensions.DBInstanceIdentifier}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.DBInstanceIdentifier",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.CPUUtilization.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.DBInstanceIdentifier:$DB_instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Operations / per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Read",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.ReadIOPS.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.DBInstanceIdentifier:$DB_instance",
     "timeField": "@timestamp"
    },
    {
     "alias": "Write",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.WriteIOPS.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.DBInstanceIdentifier:$DB_instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk latency / in ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Read",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.ReadLatency.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.DBInstanceIdentifier:$DB_instance",
     "timeField": "@timestamp"
    },
    {
     "alias": "Write",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.WriteLatency.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.DBInstanceIdentifier:$DB_instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Throughput / kb per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Read",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.ReadThroughput.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.DBInstanceIdentifier:$DB_instance",
     "timeField": "@timestamp"
    },
    {
     "alias": "Write",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.WriteThroughput.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.DBInstanceIdentifier:$DB_instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU credit usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "CPU credit usage",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.CPUCreditUsage.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "aws.cloudwatch.dimensions.DBInstanceIdentifier:$DB_instance",
     "timeField": "@timestamp"
    },
    {
     "alias": "CPU credit balance",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.CPUCreditBalance.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "aws.cloudwatch.dimensions.DBInstanceIdentifier:$DB_instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.DiskQueueDepth.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "aws.cloudwatch.dimensions.DBInstanceIdentifier:$DB_instance",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Transmit",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.NetworkTransmitThroughput.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.DBInstanceIdentifier:$DB_instance",
     "timeField": "@timestamp"
    },
    {
     "alias": "Receive",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.NetworkReceiveThroughput.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.DBInstanceIdentifier:$DB_instance",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}