{
 "title": "Cloudwatch AWS/Redshift",
 "tags": [
  "AWS",
  "Metricbeat 7.5",
  "AWS/Redshift",
  "Cloudwatch"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "clusterId",
    "label": "Cluster",
    "query": "{\"find\": \"terms\", \"field\": \"aws.cloudwatch.dimensions.ClusterIdentifier\"}"
   },
   {
    "name": "Interval",
    "query": "1s,10s,30s,1m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster HealthStatus",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "HealthStatus {{aws.cloudwatch.dimensions.ClusterIdentifier}}",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.ClusterIdentifier",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.HealthStatus.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "aws.cloudwatch.namespace:AWS\\/Redshift  AND (_exists_:aws.cloudwatch.dimensions.ClusterIdentifier AND aws.cloudwatch.dimensions.ClusterIdentifier:$clusterId)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPUUtilization/DatabaseConnections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPUUtilization {{aws.cloudwatch.dimensions.ClusterIdentifier}}",
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.ClusterIdentifier",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dimensions": { "ClusterIdentifier": "$clusteridentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "CPUUtilization",
     "metrics": [
      {
       "field": "aws.metrics.CPUUtilization.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "query": "aws.cloudwatch.namespace:AWS\\/Redshift AND (_exists_:aws.cloudwatch.dimensions.ClusterIdentifier AND aws.cloudwatch.dimensions.ClusterIdentifier:$clusterId)",
     "region": "$region",
     "statistics": [ "Average" ],
     "timeField": "@timestamp"
    },
    {
     "alias": "DatabaseConnections {{aws.cloudwatch.dimensions.ClusterIdentifier}}",
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.ClusterIdentifier",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dimensions": { "ClusterIdentifier": "$clusteridentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DatabaseConnections",
     "metrics": [
      {
       "field": "aws.metrics.DatabaseConnections.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "query": "aws.cloudwatch.namespace:AWS\\/Redshift  AND (_exists_:aws.cloudwatch.dimensions.ClusterIdentifier AND aws.cloudwatch.dimensions.ClusterIdentifier:$clusterId)",
     "region": "$region",
     "statistics": [ "Average" ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "MaintenanceMode",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "MaintenanceMode {{aws.cloudwatch.dimensions.ClusterIdentifier}}",
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.ClusterIdentifier",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dimensions": { "ClusterIdentifier": "$clusteridentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "MaintenanceMode",
     "metrics": [
      {
       "field": "aws.metrics.MaintenanceMode.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "query": "aws.cloudwatch.namespace:AWS\\/Redshift  AND (_exists_:aws.cloudwatch.dimensions.ClusterIdentifier AND aws.cloudwatch.dimensions.ClusterIdentifier:$clusterId)",
     "region": "$region",
     "statistics": [ "Average" ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "NetworkReceiveThroughput/NetworkTransmitThroughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "NetworkReceiveThroughput {{aws.cloudwatch.dimensions.ClusterIdentifier}}",
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.ClusterIdentifier",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dimensions": { "ClusterIdentifier": "$clusteridentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkReceiveThroughput",
     "metrics": [
      {
       "field": "aws.cloudwatch.metrics.NetworkReceiveThroughput$AVG",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "query": "aws.cloudwatch.namespace:AWS\\/Redshift  AND (_exists_:aws.cloudwatch.dimensions.ClusterIdentifier AND aws.cloudwatch.dimensions.ClusterIdentifier:$clusterId)",
     "region": "$region",
     "statistics": [ "Average" ],
     "timeField": "@timestamp"
    },
    {
     "alias": "NetworkTransmitThroughput {{aws.cloudwatch.dimensions.ClusterIdentifier}}",
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.ClusterIdentifier",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dimensions": { "ClusterIdentifier": "$clusteridentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkTransmitThroughput",
     "metrics": [
      {
       "field": "aws.metrics.NetworkTransmitThroughput.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "query": "aws.cloudwatch.namespace:AWS\\/Redshift  AND (_exists_:aws.cloudwatch.dimensions.ClusterIdentifier AND aws.cloudwatch.dimensions.ClusterIdentifier:$clusterId)",
     "region": "$region",
     "statistics": [ "Average" ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ReadIOPS/WriteIOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "ReadIOPS {{aws.cloudwatch.dimensions.ClusterIdentifier}}",
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.ClusterIdentifier",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dimensions": { "NodeID": "$nodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadIOPS",
     "metrics": [
      {
       "field": "aws.metrics.ReadIOPS.max",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "query": "aws.cloudwatch.namespace:AWS\\/Redshift  AND (_exists_:aws.cloudwatch.dimensions.ClusterIdentifier AND aws.cloudwatch.dimensions.ClusterIdentifier:$clusterId)",
     "region": "$region",
     "statistics": [ "Average" ],
     "timeField": "@timestamp"
    },
    {
     "alias": "WriteIOPS {{aws.cloudwatch.dimensions.ClusterIdentifier}}",
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.ClusterIdentifier",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dimensions": { "ClusterIdentifier": "$clusteridentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteIOPS",
     "metrics": [
      {
       "field": "aws.metrics.WriteIOPS.max",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "query": "aws.cloudwatch.namespace:AWS\\/Redshift  AND (_exists_:aws.cloudwatch.dimensions.ClusterIdentifier AND aws.cloudwatch.dimensions.ClusterIdentifier:$clusterId)",
     "region": "$region",
     "statistics": [ "Average" ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ReadLatency/WriteLatency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "ReadLatency {{aws.cloudwatch.dimensions.ClusterIdentifier}}",
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.ClusterIdentifier",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dimensions": { "NodeID": "$nodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadLatency",
     "metrics": [
      {
       "field": "aws.metrics.ReadLatency.max",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "query": "aws.cloudwatch.namespace:AWS\\/Redshift  AND (_exists_:aws.cloudwatch.dimensions.ClusterIdentifier AND aws.cloudwatch.dimensions.ClusterIdentifier:$clusterId)",
     "region": "$region",
     "statistics": [ "Average" ],
     "timeField": "@timestamp"
    },
    {
     "alias": "WriteLatency {{aws.cloudwatch.dimensions.ClusterIdentifier}}",
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.ClusterIdentifier",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dimensions": { "ClusterIdentifier": "$clusteridentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteLatency",
     "metrics": [
      {
       "field": "aws.metrics.WriteLatency.max",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "query": "aws.cloudwatch.namespace:AWS\\/Redshift  AND (_exists_:aws.cloudwatch.dimensions.ClusterIdentifier AND aws.cloudwatch.dimensions.ClusterIdentifier:$clusterId)",
     "region": "$region",
     "statistics": [ "Average" ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "ReadThroughput/WriteThroughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "ReadThroughput {{aws.cloudwatch.dimensions.ClusterIdentifier}}",
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.ClusterIdentifier",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dimensions": { "NodeID": "$nodeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ReadThroughput",
     "metrics": [
      {
       "field": "aws.metrics.ReadThroughput.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "query": "aws.cloudwatch.namespace:AWS\\/Redshift  AND (_exists_:aws.cloudwatch.dimensions.ClusterIdentifier AND aws.cloudwatch.dimensions.ClusterIdentifier:$clusterId)",
     "region": "$region",
     "statistics": [ "Average" ],
     "timeField": "@timestamp"
    },
    {
     "alias": "WriteThroughput {{aws.cloudwatch.dimensions.ClusterIdentifier}}",
     "application": { "filter": "" },
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.ClusterIdentifier",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "dimensions": { "ClusterIdentifier": "$clusteridentifier" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "WriteThroughput",
     "metrics": [
      {
       "field": "aws.metrics.WriteThroughput.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "namespace": "AWS/Redshift",
     "options": {
      "showDisabledItems": false
     },
     "query": "aws.cloudwatch.namespace:AWS\\/Redshift  AND (_exists_:aws.cloudwatch.dimensions.ClusterIdentifier AND aws.cloudwatch.dimensions.ClusterIdentifier:$clusterId)",
     "region": "$region",
     "statistics": [ "Average" ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Query Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "Average Query Duration",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.QueryDuration.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "aws.cloudwatch.namespace:AWS\\/Redshift",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Queries Completed Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Queries Completed Per Second",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$Interval", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.QueriesCompletedPerSecond.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "aws.cloudwatch.namespace:AWS\\/Redshift",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}