{
 "title": "Cloudwatch AWS/S3",
 "description": "This dashboard fetch data from Cloudwatch AWS/S3 namespace",
 "tags": [
  "AWS",
  "AWS/S3",
  "Metricbeat 7.5",
  "Cloudwatch"
 ],
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "elasticsearch" },
   {
    "name": "Region",
    "query": "{ \"find\": \"terms\", \"field\": \"cloud.region\", \"size\":1000 }"
   },
   {
    "name": "Bucket_name",
    "query": "{ \"find\": \"terms\", \"field\": \"aws.cloudwatch.dimensions.BucketName\", \"query\":\"cloud.region:$Region\"}"
   }
  ]
 },
 "panels": [
  { "title": "S3 request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{aws.cloudwatch.dimensions.BucketName}} - 4XX",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.BucketName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.4xxErrors.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "cloud.region:$Region",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{aws.cloudwatch.dimensions.BucketName}} - 5XX",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.BucketName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.5xxErrors.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "cloud.region:$Region",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{aws.cloudwatch.dimensions.BucketName}} - Total requests",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.BucketName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.AllRequests.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "cloud.region:$Region",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Filtered latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{aws.cloudwatch.dimensions.BucketName}} - First byte latency",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.BucketName",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.FirstByteLatency.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "cloud.region:$Region",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{aws.cloudwatch.dimensions.BucketName}} - Total request latency",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.BucketName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.TotalRequestLatency.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "cloud.region:$Region",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Filtered bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{aws.cloudwatch.dimensions.BucketName}} - Downloaded",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.BucketName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.BytesDownloaded.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "cloud.region:$Region",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{aws.cloudwatch.dimensions.BucketName}} - Uploaded",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.BucketName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.s3_request.uploaded.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "cloud.region:$Region",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Put requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{aws.cloudwatch.dimensions.BucketName}} - Put requests",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.BucketName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.PutRequests.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "cloud.region:$Region",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "List requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{aws.cloudwatch.dimensions.BucketName}} - List requests",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.BucketName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.ListRequests.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "cloud.region:$Region",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Head requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{aws.cloudwatch.dimensions.BucketName}} - Head requests",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.BucketName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.HeadRequests.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "cloud.region:$Region",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Get requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{aws.cloudwatch.dimensions.BucketName}} - Get requests",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.BucketName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.GetRequests.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "cloud.region:$Region",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "S3 daily storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Size in bytes by S3 Bucket ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.BucketName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.BucketSizeBytes.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total size ",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 37 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.BucketSizeBytes.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of objects by S3 bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.BucketName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "aws.metrics.NumberOfObjects.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.BucketName:$Bucket_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total number of objects",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 45 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.NumberOfObjects.avg",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}