{
 "title": "Cloudwatch AWS/EC2",
 "tags": [
  "AWS",
  "Cloudwatch",
  "metricbeat 7.5",
  "AWS/EC2"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "elasticsearch" },
   {
    "name": "Region",
    "query": "{ \"find\": \"terms\", \"field\": \"cloud.region\"}"
   },
   {
    "name": "Instance_id",
    "query": "{ \"find\": \"terms\", \"field\": \"aws.cloudwatch.dimensions.InstanceId\",\"query\":\"cloud.region:$Region\"}"
   },
   { "name": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Advanced EC2 metrics (cloudwatch agent)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory used precent",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.InstanceId",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.mem_used_percent.avg",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "avg"
        }
       ],
       "query": "aws.cloudwatch.dimensions.InstanceId:$Instance_id AND _exists_:aws.metrics.mem_used_percent.sum",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Used Swap percentage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.InstanceId",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.swap_used_percent.avg",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.dimensions.InstanceId:$Instance_id AND _exists_:aws.metrics.swap_used_percent.sum",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Disk IO time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.InstanceId",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.diskio_io_time.avg",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.dimensions.InstanceId:$Instance_id AND _exists_:aws.metrics.diskio_io_time.sum",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Disk used precent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "aws.cloudwatch.dimensions.InstanceId",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.disk_used_percent.avg",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.dimensions.InstanceId:$Instance_id AND _exists_:aws.metrics.disk_used_percent.sum",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Index nodes free",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 21, "y": 10 },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 1 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "aws.metrics.disk_inodes_free.sum",
         "id": "1",
         "meta": {},
         "settings": {},
         "type": "sum"
        }
       ],
       "query": "aws.cloudwatch.dimensions.InstanceId:$Instance_id AND _exists_:aws.metrics.disk_inodes_free.sum",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "EC2 CPU & Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "EC2 CPU utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.InstanceId",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.CPUUtilization.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.InstanceId:$Instance_id",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Running instances (Max)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 2 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.ec2.instance.state.name",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "aws.cloudwatch.dimensions.InstanceId:$Instance_id",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "EC2 network bytes in / out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "{{aws.cloudwatch.dimensions.InstanceId}} - In",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.InstanceId",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.NetworkIn.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.InstanceId:$Instance_id",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{aws.cloudwatch.dimensions.InstanceId}} - Out",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.InstanceId",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.NetworkOut.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.InstanceId:$Instance_id",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "EC2 network packets in / out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{aws.cloudwatch.dimensions.InstanceId}} - in",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.InstanceId",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "aws.metrics.NetworkPacketsIn.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.InstanceId:$Instance_id",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{aws.cloudwatch.dimensions.InstanceId}} - out",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.InstanceId",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "aws.metrics.NetworkPacketsOut.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.InstanceId:$Instance_id",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "EC2 Disk io read/write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.DiskWriteBytes.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "aws.metrics.DiskReadBytes.avg",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.InstanceId:$Instance_id",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "EC2 CPU credit balance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.CPUCreditBalance.avg",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "aws.metrics.CPUCreditUsage.avg",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "aws.cloudwatch.dimensions.InstanceId:$Instance_id",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "EC2 CPU credit ussge",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 1,
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "aws.ec2.cpu.credit_balance",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "aws.metrics.CPUCreditUsage.avg",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "aws.cloudwatch.dimensions.InstanceId:$Instance_id",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "EC2 Status check failed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.StatusCheckFailed.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "aws.metrics.StatusCheckFailed_Instance.sum",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "aws.metrics.StatusCheckFailed_System.sum",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}