{
 "title": "Cloudwatch AWS/Lambda",
 "tags": [
  "AWS",
  "Lambda",
  "Metricbeat 7.4"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Darasource", "query": "elasticsearch" },
   {
    "name": "Region",
    "query": "{ \"find\": \"terms\", \"field\": \"cloud.region\", \"size\":1000 }"
   },
   {
    "name": "Function_Name",
    "query": "{ \"find\": \"terms\", \"field\": \"aws.cloudwatch.dimensions.FunctionName\", \"query\":\"cloud.region:$Region\" }"
   },
   {
    "name": "Resource",
    "query": "{ \"find\": \"terms\", \"field\": \"aws.cloudwatch.dimensions.Resource\", \"query\":\"cloud.region:$Region\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Invocations and Errors by function",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{aws.cloudwatch.dimensions.FunctionName}} - Invocations",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.FunctionName",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.Invocations.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.Resource:$Resource",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{aws.cloudwatch.dimensions.FunctionName}} - Errors",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.FunctionName",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.Errors.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.Resource:$Resource",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Success rate (%) by function",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "{{aws.cloudwatch.dimensions.FunctionName}} - Sucsess rate",
     "bucketAggs": [
      {
       "fake": true,
       "field": "aws.cloudwatch.dimensions.FunctionName",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.Errors.sum",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "aws.metrics.Invocations.sum",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "select field",
       "id": "4",
       "meta": {},
       "pipelineVariables": [
        { "name": "Errors", "pipelineAgg": "1" },
        { "name": "Invocations", "pipelineAgg": "3" }
       ],
       "settings": {
        "script": "1 - (params.Errors / params.Invocations)"
       },
       "type": "bucket_script"
      }
     ],
     "query": "aws.cloudwatch.dimensions.Resource:$Resource",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.Errors.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total invocations",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 1 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.Invocations.sum",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "aws.cloudwatch.dimensions.FunctionName:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Duration ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.Duration.avg",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.Resource:$Resource",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.Duration.max",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.Resource:$Resource",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.metrics.Duration.min",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.Resource:$Resource",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Throttles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.cloudwatch.metrics.Throttles",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "aws.cloudwatch.dimensions.Resource:$Resource",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Concurrent executions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "aws.cloudwatch.metrics.ConcurrentExecutions",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "aws.cloudwatch.metrics.UnreservedConcurrentExecutions",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}